name: Build Portable CreatureRoller App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Portable Application
      run: dotnet publish -c Release -r win-x64 --self-contained -o ./CreatureRoller-portable

    - name: Zip Build Artifacts
      run: Compress-Archive -Path ./CreatureRoller-portable/* -DestinationPath ./CreatureRoller-portable.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CreatureRoller
        path: ./CreatureRoller-portable.zip
