name: Build and Publish CreatureRoller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish the application
      run: dotnet publish -c Release -r win-x64 --self-contained --output ./output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CreatureRoller
        path: ./output
